---
- name: Start services via docker-compose
  command: |
    bash -lc "cd {{ project_path }} \
    && docker-compose -f docker-compose.mac.yml up -d"
  environment:
    PATH: "{{ lookup('env','PATH') }}"
  changed_when: false
